version: '{build}'
skip_tags: true
image:
  - Visual Studio 2019
  - Ubuntu1804
configuration: Release
test: false
install:
  - ps: ./setup.ps1
build_script:
  - ps: dotnet --info
  - ps: dotnet --list-sdks
  - ps: ./build.ps1
for:
-
  matrix:
    only:
      - image: Ubuntu1804
  install:
  - sh setup.sh
  build_script:
  - dotnet --info
  - dotnet --list-sdks
  - pwsh -v
  - sh build.sh
artifacts:
- path: artifacts/Kmd.Logic.Sms*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: ni2oke06kymckw907gql5g4f
  skip_symbols: true
  on:
    branch: /^(master|dev)$/
    CI_WINDOWS: true
- provider: GitHub
  auth_token:
    secure: 5b6c52df53064b9fc20c9ea9090b8d95853d4b8c 
  artifact: /Kmd.Logic.Sms.Client.*\.nupkg/
  tag: v$(appveyor_build_version)
  on:
    branch: master
    CI_WINDOWS: true
